# Nome exibido na aba 'Actions' do GitHub name: CI - Integração Contínua Docker 

# Trigger: Dispara a pipeline a cada push realizado na branch main on: push: branches: [ "main" ] # Trabalhos que a pipeline vai executar jobs: build-and-test: 

# Agente de execução (Runner em máquina Linux Ubuntu) runs-on: ubuntu-latest steps: 

# Step 1: Baixa o código-fonte do repositório para a máquina virtual - name: Checkout do Código uses: actions/checkout@v3 

# Step 2: Configura o ambiente com Node.js versão 18 - name: Configurar ambiente Node.js uses: actions/setup-node@v3 with: node-version: '18' 

# Step 3: Instala as dependências listadas no package.json - name: Instalar Dependências da Aplicação run: npm install 

# Step 4: Testa a construção da Imagem Docker a partir do Dockerfile - name: Build da Imagem Docker run: docker build -t nttdata-servidor:ci .
