name: CI - Projeto Integrado Semana 7

on:
  push:
    branches:
      - "develop"
      - "main"
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./projeto-integrado

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Validar sintaxe do Docker Compose
        run: docker compose config

      - name: Testar Build e Execução dos Containers
        run: |
          docker compose up -d --build
          docker compose ps
          docker compose down